name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate-formula:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Validate formula syntax
      run: |
        echo "::group::Validating formula syntax"
        # Set environment variable to use local formula instead of API
        export HOMEBREW_NO_INSTALL_FROM_API=1
        
        # Create a temporary tap for formula validation
        echo "Creating temporary tap for formula validation..."
        brew tap-new test-folder2md4llms/tap --no-git
        
        # Copy formula to temporary tap
        cp ./Formula/folder2md4llms.rb $(brew --repository)/Library/Taps/test-folder2md4llms/homebrew-tap/Formula/
        
        # Run audit on the formula by name
        echo "Running formula audit..."
        brew audit --strict --formula test-folder2md4llms/tap/folder2md4llms
        
        # Clean up temporary tap
        echo "Cleaning up temporary tap..."
        brew untap test-folder2md4llms/tap
        echo "::endgroup::"
    
    - name: Check formula dependencies
      run: |
        echo "::group::Checking formula dependencies"
        # Extract dependencies from formula
        echo "Dependencies listed in formula:"
        grep -A 50 "depends_on" ./Formula/folder2md4llms.rb | head -20
        
        echo "Resources (Python packages) listed in formula:"
        grep -A 3 "resource \"" ./Formula/folder2md4llms.rb
        
        # Verify we only have core dependencies
        if grep -q "maturin\|cryptography\|rust" ./Formula/folder2md4llms.rb; then
          echo "❌ ERROR: Formula contains problematic dependencies!"
          echo "Found problematic dependencies:"
          grep -n "maturin\|cryptography\|rust" ./Formula/folder2md4llms.rb
          exit 1
        else
          echo "✅ Formula contains only core dependencies"
        fi
        echo "::endgroup::"
    
    - name: Test formula installation
      run: |
        echo "::group::Testing formula installation"
        start_time=$(date +%s)
        
        # Set environment variable to use local formula instead of API
        export HOMEBREW_NO_INSTALL_FROM_API=1
        
        # Install the formula
        brew install --build-from-source ./Formula/folder2md4llms.rb
        
        end_time=$(date +%s)
        echo "Installation completed in $((end_time - start_time)) seconds"
        
        # Quick functionality test
        folder2md --version
        folder2md --help
        
        echo "✅ Formula installation and basic functionality verified"
        echo "::endgroup::"
    
    - name: Cleanup
      if: always()
      run: |
        echo "::group::Cleanup"
        brew uninstall folder2md4llms || true
        echo "::endgroup::"

  check-workflows:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Validate workflow files
      run: |
        echo "::group::Validating workflow files"
        
        # Check that all workflow files are valid YAML
        for workflow in .github/workflows/*.yml; do
          echo "Checking $workflow..."
          if ! python -c "import yaml; yaml.safe_load(open('$workflow'))"; then
            echo "❌ ERROR: $workflow is not valid YAML!"
            exit 1
          else
            echo "✅ $workflow is valid YAML"
          fi
        done
        
        # Check that workflows have required fields
        for workflow in .github/workflows/*.yml; do
          echo "Checking required fields in $workflow..."
          
          if ! grep -q "^name:" "$workflow"; then
            echo "❌ ERROR: $workflow missing 'name' field"
            exit 1
          fi
          
          if ! grep -q "^on:" "$workflow"; then
            echo "❌ ERROR: $workflow missing 'on' field"
            exit 1
          fi
          
          if ! grep -q "^jobs:" "$workflow"; then
            echo "❌ ERROR: $workflow missing 'jobs' field"
            exit 1
          fi
          
          echo "✅ $workflow has required fields"
        done
        
        echo "::endgroup::"
    
    - name: Summary
      run: |
        echo "::group::Summary"
        echo "✅ All workflow files are valid"
        echo "✅ Formula syntax is valid"
        echo "✅ Formula contains only core dependencies"
        echo "✅ CI pipeline is working correctly"
        echo "::endgroup::"