name: Issue Handler

on:
  issues:
    types: [opened, reopened]
  issue_comment:
    types: [created]

jobs:
  handle-installation-issues:
    if: contains(github.event.issue.title, 'install') || contains(github.event.issue.body, 'install') || contains(github.event.issue.title, 'error') || contains(github.event.issue.body, 'maturin') || contains(github.event.issue.body, 'cryptography')
    runs-on: ubuntu-latest
    
    steps:
    - name: Check for installation issues
      uses: actions/github-script@v7
      with:
        script: |
          const issue = context.payload.issue;
          const body = issue.body.toLowerCase();
          const title = issue.title.toLowerCase();
          
          // Check for common installation issues
          const isInstallationIssue = title.includes('install') || body.includes('install');
          const isMaturinIssue = body.includes('maturin') || body.includes('rust');
          const isCryptographyIssue = body.includes('cryptography') || body.includes('openssl');
          const isCompilationIssue = body.includes('compilation') || body.includes('build');
          
          let response = '';
          let labels = ['bug'];
          
          if (isInstallationIssue) {
            labels.push('installation');
            
            if (isMaturinIssue || isCryptographyIssue || isCompilationIssue) {
              labels.push('dependency-issue');
              response = `
          Hi! It looks like you're experiencing an installation issue that may be related to complex dependencies.
          
          ## Quick Fix
          
          The simplified Homebrew formula should resolve this issue. Please try:
          
          \`\`\`bash
          # If you have a previous installation, remove it first
          brew uninstall folder2md4llms
          
          # Install the simplified version
          brew install henriqueslab/folder2md4llms/folder2md4llms
          \`\`\`
          
          ## What Changed
          
          We've simplified the Homebrew formula to only include core dependencies:
          - ✅ click, pyyaml, rich, markdown-it-py, mdurl, pygments
          - ❌ No more maturin, cryptography, or Rust dependencies
          
          This should eliminate compilation issues and make installation much more reliable.
          
          ## If You Still Have Issues
          
          If the simplified installation doesn't work, please provide:
          1. Your OS version: \`sw_vers\` (macOS) or \`lsb_release -a\` (Linux)
          2. Homebrew version: \`brew --version\`
          3. Full installation output: \`brew install henriqueslab/folder2md4llms/folder2md4llms 2>&1\`
          
          Our CI tests validate the installation on macOS 13, macOS 14, and Ubuntu, so it should work reliably.
              `.trim();
            } else {
              response = `
          Hi! Thanks for reporting this installation issue.
          
          ## First Steps
          
          Please try the latest simplified formula:
          
          \`\`\`bash
          # If you have a previous installation, remove it first
          brew uninstall folder2md4llms
          
          # Install the simplified version
          brew install henriqueslab/folder2md4llms/folder2md4llms
          \`\`\`
          
          ## Troubleshooting
          
          If you continue to have issues, please provide:
          1. Your OS version
          2. Homebrew version
          3. Full installation output
          
          The simplified formula has been tested on multiple platforms and should install reliably.
              `.trim();
            }
          }
          
          if (response) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: response
            });
            
            // Add labels
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: labels
            });
          }

  test-user-installation:
    if: contains(github.event.issue.body, 'test-installation')
    runs-on: macos-latest
    
    steps:
    - name: Test installation as reported by user
      run: |
        echo "::group::Testing user-reported installation issue"
        
        # Try to reproduce the issue
        echo "Installing folder2md4llms..."
        if brew install henriqueslab/folder2md4llms/folder2md4llms; then
          echo "✅ Installation successful"
          
          # Test basic functionality
          folder2md --version
          folder2md --help
          
          # Create test files
          mkdir test-dir
          echo "print('test')" > test-dir/test.py
          
          # Test conversion
          folder2md test-dir --output test.md
          
          if [ -f test.md ]; then
            echo "✅ Basic functionality works"
          else
            echo "❌ Basic functionality failed"
            exit 1
          fi
          
        else
          echo "❌ Installation failed"
          exit 1
        fi
        
        echo "::endgroup::"
    
    - name: Report test results
      if: always()
      uses: actions/github-script@v7
      with:
        script: |
          const issue = context.payload.issue;
          const jobStatus = '${{ job.status }}';
          
          let response = '';
          
          if (jobStatus === 'success') {
            response = `
          ## Installation Test Results ✅
          
          I've tested the installation on macOS and it completed successfully:
          - ✅ Formula installed without errors
          - ✅ folder2md command works correctly
          - ✅ Basic functionality verified
          
          The simplified formula appears to be working correctly. Could you please try again with:
          
          \`\`\`bash
          brew uninstall folder2md4llms  # Remove any existing installation
          brew install henriqueslab/folder2md4llms/folder2md4llms
          \`\`\`
          
          If you still encounter issues, please provide your system details as requested above.
            `.trim();
          } else {
            response = `
          ## Installation Test Results ❌
          
          I was able to reproduce the installation issue on macOS. This indicates a real problem that needs to be addressed.
          
          I'll investigate this issue and provide a fix as soon as possible.
          
          Thank you for reporting this!
            `.trim();
          }
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue.number,
            body: response
          });